// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: test/codecs_test.proto

package test

import (
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"

	pmongo "github.com/bit-one/mgd-proto/pmongo"
	types "github.com/gogo/protobuf/types"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	BoolValue            *types.BoolValue   `protobuf:"bytes,1,opt,name=boolValue,proto3" json:"boolValue,omitempty"`
	BytesValue           *types.BytesValue  `protobuf:"bytes,2,opt,name=bytesValue,proto3" json:"bytesValue,omitempty"`
	DoubleValue          *types.DoubleValue `protobuf:"bytes,3,opt,name=doubleValue,proto3" json:"doubleValue,omitempty"`
	FloatValue           *types.FloatValue  `protobuf:"bytes,4,opt,name=floatValue,proto3" json:"floatValue,omitempty"`
	Int32Value           *types.Int32Value  `protobuf:"bytes,5,opt,name=int32Value,proto3" json:"int32Value,omitempty"`
	Int64Value           *types.Int64Value  `protobuf:"bytes,6,opt,name=int64Value,proto3" json:"int64Value,omitempty"`
	StringValue          *types.StringValue `protobuf:"bytes,7,opt,name=stringValue,proto3" json:"stringValue,omitempty"`
	Uint32Value          *types.UInt32Value `protobuf:"bytes,8,opt,name=uint32Value,proto3" json:"uint32Value,omitempty"`
	Uint64Value          *types.UInt64Value `protobuf:"bytes,9,opt,name=uint64Value,proto3" json:"uint64Value,omitempty"`
	Timestamp            *types.Timestamp   `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Id                   *pmongo.ObjectId   `protobuf:"bytes,11,opt,name=id,proto3" json:"id,omitempty"`
	Listvalue            *types.ListValue   `protobuf:"bytes,12,opt,name=listvalue,proto3" json:"listvalue,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-" bson:"-"`
	XXX_unrecognized     []byte             `json:"-" bson:"-"`
	XXX_sizecache        int32              `json:"-" bson:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_43810f7b7fa1e32d, []int{0}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Data.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return m.Size()
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetBoolValue() *types.BoolValue {
	if m != nil {
		return m.BoolValue
	}
	return nil
}

func (m *Data) GetBytesValue() *types.BytesValue {
	if m != nil {
		return m.BytesValue
	}
	return nil
}

func (m *Data) GetDoubleValue() *types.DoubleValue {
	if m != nil {
		return m.DoubleValue
	}
	return nil
}

func (m *Data) GetFloatValue() *types.FloatValue {
	if m != nil {
		return m.FloatValue
	}
	return nil
}

func (m *Data) GetInt32Value() *types.Int32Value {
	if m != nil {
		return m.Int32Value
	}
	return nil
}

func (m *Data) GetInt64Value() *types.Int64Value {
	if m != nil {
		return m.Int64Value
	}
	return nil
}

func (m *Data) GetStringValue() *types.StringValue {
	if m != nil {
		return m.StringValue
	}
	return nil
}

func (m *Data) GetUint32Value() *types.UInt32Value {
	if m != nil {
		return m.Uint32Value
	}
	return nil
}

func (m *Data) GetUint64Value() *types.UInt64Value {
	if m != nil {
		return m.Uint64Value
	}
	return nil
}

func (m *Data) GetTimestamp() *types.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Data) GetId() *pmongo.ObjectId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Data) GetListvalue() *types.ListValue {
	if m != nil {
		return m.Listvalue
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "test.Data")
}

func init() { proto.RegisterFile("test/codecs_test.proto", fileDescriptor_43810f7b7fa1e32d) }

var fileDescriptor_43810f7b7fa1e32d = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd2, 0x4d, 0x4b, 0xc3, 0x30,
	0x18, 0xc0, 0x71, 0x3b, 0xb7, 0xe9, 0x32, 0x0f, 0xa3, 0xa0, 0x8c, 0x39, 0xea, 0xf0, 0xe4, 0xa9,
	0x85, 0x4d, 0x44, 0x10, 0x3c, 0x8c, 0x21, 0x0c, 0x04, 0x21, 0xbe, 0x5c, 0xa5, 0x2f, 0x59, 0x89,
	0x74, 0x4b, 0x69, 0x9e, 0x2a, 0x7e, 0x13, 0x3f, 0x92, 0x78, 0xf2, 0x23, 0xc8, 0xfc, 0x22, 0x92,
	0xa4, 0x2f, 0x61, 0x23, 0xde, 0x4a, 0xf7, 0xff, 0x35, 0x4f, 0xd8, 0x83, 0x8e, 0x80, 0x70, 0xf0,
	0x42, 0x16, 0x91, 0x90, 0x3f, 0x8b, 0x67, 0x37, 0xcd, 0x18, 0x30, 0xbb, 0x29, 0x9e, 0x07, 0x27,
	0x31, 0x63, 0x71, 0x42, 0x3c, 0xf9, 0x2e, 0xc8, 0x17, 0x1e, 0xd0, 0x25, 0xe1, 0xe0, 0x2f, 0x53,
	0x95, 0x0d, 0x9c, 0xcd, 0xe0, 0x2d, 0xf3, 0xd3, 0x94, 0x64, 0xbc, 0xf8, 0xfd, 0x30, 0x5d, 0xb2,
	0x55, 0xcc, 0x3c, 0x16, 0xbc, 0x90, 0x10, 0x68, 0x54, 0xbc, 0x1e, 0x6e, 0x32, 0x0e, 0x59, 0x1e,
	0x16, 0x67, 0x9f, 0x7e, 0xb5, 0x50, 0x73, 0xe6, 0x83, 0x6f, 0x5f, 0xa2, 0x4e, 0xc0, 0x58, 0xf2,
	0xe4, 0x27, 0x39, 0xe9, 0x5b, 0x23, 0xeb, 0xac, 0x3b, 0x1e, 0xb8, 0x8a, 0xba, 0x25, 0x75, 0xa7,
	0x65, 0x81, 0xeb, 0xd8, 0xbe, 0x42, 0x28, 0x78, 0x07, 0xc2, 0x15, 0x6d, 0x48, 0x7a, 0xbc, 0x4d,
	0xab, 0x04, 0x6b, 0xb9, 0x7d, 0x8d, 0xba, 0x11, 0xcb, 0x83, 0x84, 0x28, 0xbd, 0x2b, 0xf5, 0x70,
	0x4b, 0xcf, 0xea, 0x06, 0xeb, 0x40, 0x1c, 0xbe, 0x48, 0x98, 0x0f, 0x8a, 0x37, 0x0d, 0x87, 0xdf,
	0x54, 0x09, 0xd6, 0x72, 0x81, 0xe9, 0x0a, 0x26, 0x63, 0x85, 0x5b, 0x06, 0x3c, 0xaf, 0x12, 0xac,
	0xe5, 0x05, 0xbe, 0x38, 0x57, 0xb8, 0x6d, 0xc6, 0x45, 0x82, 0xb5, 0x5c, 0x5c, 0x9b, 0x43, 0x46,
	0x57, 0xb1, 0xd2, 0x7b, 0x86, 0x6b, 0xdf, 0xd7, 0x0d, 0xd6, 0x81, 0xf0, 0xb9, 0x36, 0xfa, 0xbe,
	0xc1, 0x3f, 0x6a, 0xb3, 0xeb, 0xa0, 0xf4, 0xe5, 0xf4, 0x9d, 0x7f, 0x7c, 0x39, 0xbe, 0x0e, 0xc4,
	0xb6, 0x54, 0xeb, 0xd9, 0x47, 0x86, 0x6d, 0x79, 0x28, 0x0b, 0x5c, 0xc7, 0xf6, 0x08, 0x35, 0x68,
	0xd4, 0xef, 0x4a, 0xd2, 0x73, 0xd5, 0xca, 0xba, 0x77, 0x72, 0x65, 0xe7, 0x11, 0x6e, 0xd0, 0x48,
	0x7c, 0x3b, 0xa1, 0x1c, 0x5e, 0xe5, 0x64, 0x07, 0x86, 0x6f, 0xdf, 0x52, 0x5e, 0xfc, 0xa1, 0x75,
	0x3c, 0xed, 0x7d, 0xae, 0x1d, 0xeb, 0x7b, 0xed, 0x58, 0x3f, 0x6b, 0xc7, 0xfa, 0xf8, 0x75, 0x76,
	0x82, 0xb6, 0x04, 0x93, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xfe, 0x1a, 0xd7, 0x7b, 0x03,
	0x00, 0x00,
}

func (m *Data) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Data) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Data) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Listvalue != nil {
		{
			size, err := m.Listvalue.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCodecsTest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x62
	}
	if m.Id != nil {
		{
			size, err := m.Id.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCodecsTest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if m.Timestamp != nil {
		{
			size, err := m.Timestamp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCodecsTest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if m.Uint64Value != nil {
		{
			size, err := m.Uint64Value.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCodecsTest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.Uint32Value != nil {
		{
			size, err := m.Uint32Value.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCodecsTest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.StringValue != nil {
		{
			size, err := m.StringValue.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCodecsTest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.Int64Value != nil {
		{
			size, err := m.Int64Value.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCodecsTest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.Int32Value != nil {
		{
			size, err := m.Int32Value.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCodecsTest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.FloatValue != nil {
		{
			size, err := m.FloatValue.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCodecsTest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.DoubleValue != nil {
		{
			size, err := m.DoubleValue.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCodecsTest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.BytesValue != nil {
		{
			size, err := m.BytesValue.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCodecsTest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.BoolValue != nil {
		{
			size, err := m.BoolValue.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintCodecsTest(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCodecsTest(dAtA []byte, offset int, v uint64) int {
	offset -= sovCodecsTest(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Data) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BoolValue != nil {
		l = m.BoolValue.Size()
		n += 1 + l + sovCodecsTest(uint64(l))
	}
	if m.BytesValue != nil {
		l = m.BytesValue.Size()
		n += 1 + l + sovCodecsTest(uint64(l))
	}
	if m.DoubleValue != nil {
		l = m.DoubleValue.Size()
		n += 1 + l + sovCodecsTest(uint64(l))
	}
	if m.FloatValue != nil {
		l = m.FloatValue.Size()
		n += 1 + l + sovCodecsTest(uint64(l))
	}
	if m.Int32Value != nil {
		l = m.Int32Value.Size()
		n += 1 + l + sovCodecsTest(uint64(l))
	}
	if m.Int64Value != nil {
		l = m.Int64Value.Size()
		n += 1 + l + sovCodecsTest(uint64(l))
	}
	if m.StringValue != nil {
		l = m.StringValue.Size()
		n += 1 + l + sovCodecsTest(uint64(l))
	}
	if m.Uint32Value != nil {
		l = m.Uint32Value.Size()
		n += 1 + l + sovCodecsTest(uint64(l))
	}
	if m.Uint64Value != nil {
		l = m.Uint64Value.Size()
		n += 1 + l + sovCodecsTest(uint64(l))
	}
	if m.Timestamp != nil {
		l = m.Timestamp.Size()
		n += 1 + l + sovCodecsTest(uint64(l))
	}
	if m.Id != nil {
		l = m.Id.Size()
		n += 1 + l + sovCodecsTest(uint64(l))
	}
	if m.Listvalue != nil {
		l = m.Listvalue.Size()
		n += 1 + l + sovCodecsTest(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovCodecsTest(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCodecsTest(x uint64) (n int) {
	return sovCodecsTest(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Data) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCodecsTest
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Data: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Data: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BoolValue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodecsTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodecsTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodecsTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BoolValue == nil {
				m.BoolValue = &types.BoolValue{}
			}
			if err := m.BoolValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BytesValue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodecsTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodecsTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodecsTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BytesValue == nil {
				m.BytesValue = &types.BytesValue{}
			}
			if err := m.BytesValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DoubleValue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodecsTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodecsTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodecsTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DoubleValue == nil {
				m.DoubleValue = &types.DoubleValue{}
			}
			if err := m.DoubleValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FloatValue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodecsTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodecsTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodecsTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.FloatValue == nil {
				m.FloatValue = &types.FloatValue{}
			}
			if err := m.FloatValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Int32Value", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodecsTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodecsTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodecsTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Int32Value == nil {
				m.Int32Value = &types.Int32Value{}
			}
			if err := m.Int32Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Int64Value", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodecsTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodecsTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodecsTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Int64Value == nil {
				m.Int64Value = &types.Int64Value{}
			}
			if err := m.Int64Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StringValue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodecsTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodecsTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodecsTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StringValue == nil {
				m.StringValue = &types.StringValue{}
			}
			if err := m.StringValue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uint32Value", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodecsTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodecsTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodecsTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Uint32Value == nil {
				m.Uint32Value = &types.UInt32Value{}
			}
			if err := m.Uint32Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uint64Value", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodecsTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodecsTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodecsTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Uint64Value == nil {
				m.Uint64Value = &types.UInt64Value{}
			}
			if err := m.Uint64Value.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodecsTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodecsTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodecsTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Timestamp == nil {
				m.Timestamp = &types.Timestamp{}
			}
			if err := m.Timestamp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodecsTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodecsTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodecsTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Id == nil {
				m.Id = &pmongo.ObjectId{}
			}
			if err := m.Id.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Listvalue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCodecsTest
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCodecsTest
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCodecsTest
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Listvalue == nil {
				m.Listvalue = &types.ListValue{}
			}
			if err := m.Listvalue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCodecsTest(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthCodecsTest
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthCodecsTest
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCodecsTest(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCodecsTest
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCodecsTest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCodecsTest
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCodecsTest
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCodecsTest
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCodecsTest
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCodecsTest        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCodecsTest          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCodecsTest = fmt.Errorf("proto: unexpected end of group")
)
